### ISSUE TITLE
cannot type @

### ISSUE THREAD

**Issue by jlgeering** [atom/open-on-github#49] opened 2015-08-18 06:45 UTC
alt-g is how you type @ on swiss keyboard

disabling the package did not help, had to create a keymap entry:

'atom-text-editor':
  'alt-g': 'native!'

**Comment by jlgeering** [comment] 2015-08-18 06:49
well after also disabling git-diff package, I don't need the keymap anymore.

=> add an option to change the default keybinding?
=> ignore and close?

**Comment by mnquintana** [comment] 2015-08-18 10:21
This looks like a duplicate of https://github.com/atom/atom-keymap/issues/35 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-18 10:21 UTC

**Comment by jlgeering** [comment] 2015-08-18 21:33
in case anybody ends up here, this seems like a more helpful link: https://atom.io/packages/keyboard-localization

**Comment by mediafreakch** [comment] 2015-08-19 12:15
same here. 

@jlgeering How was the package you linked to useful to you? Which locale do you use to enable @ key on ALT + G ?

**Comment by jlgeering** [comment] 2015-08-20 06:40
@mediafreakch locale? no clue, nothing special, i.e. don't know how to change / configure locale in atom.

right now I'm happy with just an entry in keymap.cson (see above) haven't tried the package yet.
