### ISSUE TITLE
Keybindings interfere with @-character on OSX

### ISSUE THREAD

**Issue by LukasSkywalker** [atom/open-on-github#44] opened 2015-06-17 06:50 UTC
On OSX, the @-character is written by pressing <kbd>Alt</kbd>+<kbd>G</kbd> (at least on a german keyboard). If open-in-github is installed, this key combo needs to be pressed twice for the @-character to appear. I suspect it's because open-on-github has keybindings for <kbd>Alt</kbd>+<kbd>G</kbd>,<kbd>B</kbd> and similar.

**Comment by 50Wliu** [comment] 2015-06-17 13:34
Duplicate of atom/atom-keymap#35, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-17 13:34 UTC

**Comment by LukasSkywalker** [comment] 2015-06-17 14:25
I think it's not the same. atom/atom-keymap#35 deals with users not being able to write the @-char using the right Alt (or AltGr) key at all. I am able to write @ as long as I disable open-on-github. It's open-on-github's keybindings which interfere with the way German OSX-users type the @-char.
